"""update_chat_session_table_with_summary_column

Revision ID: cfe09ef4ac80
Revises: d2a09e131fba
Create Date: 2026-06-04 20:39:43.469079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfe09ef4ac80'
down_revision: Union[str, Sequence[str], None] = 'd2a09e131fba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_session', sa.Column('session_summary', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_session', 'session_summary')
    # ### end Alembic commands ###
