"""make_summary_nulable

Revision ID: d410505c4f45
Revises: 1c32556ab4ff
Create Date: 2026-06-05 23:50:20.965059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd410505c4f45'
down_revision: Union[str, Sequence[str], None] = '1c32556ab4ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_session', 'session_title',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('chat_session', 'session_summary',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_session', 'session_summary',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chat_session', 'session_title',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    # ### end Alembic commands ###
