"""Add cascade delete to conversation foreign key

Revision ID: dbbb16bb9545
Revises: 12ef279c0370
Create Date: 2026-06-06 14:47:20.783722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbbb16bb9545'
down_revision: Union[str, Sequence[str], None] = '12ef279c0370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('conversation_session_id_fkey'), 'conversation', type_='foreignkey')
    op.create_foreign_key(None, 'conversation', 'chat_session', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversation', type_='foreignkey')
    op.create_foreign_key(op.f('conversation_session_id_fkey'), 'conversation', 'chat_session', ['session_id'], ['id'])
    # ### end Alembic commands ###
